### ISSUE TITLE
show method & AM, PM

### ISSUE THREAD

**Issue by achchu93** [loebi-ch/jquery-clock-timepicker#10]
Nice plugin and good work. But it is appreciated if we can manually trigger the time picker with show method. And i would love if i can have AM, PM option instead of 24 hours format circle.

Good Luck.

**Comment by loebi-ch** [comment]
Thank you for the compliment.

The option with AM/PM has been planned since beginning of coding this plugin, but neither I nor others had a demand for that. Currently I don't find the time to include this, but I'm going to put this feature request on the top of my TODO list. (See #1 for details)

Concerning the issue with manually triggering the time picker, I have a solution for you:

After instanciating the clockTimePicker by using i.e...

```
$('#myTimepicker').clockTimePicker();
```

...you can use the following code to manually show up the clock time picker popup:

```
$('#myTimepicker').focus();
```

One thing to remark:
If there is no time passing between the two commands (in case that you instanciate and directly want to show the time picker popup), you must use a timeout:

```
setTimeout(function() {
  $('#myTimepicker').focus();
}, 1);
```

Best regards,
Andy

**Comment by loebi-ch** [comment]
#1
